version: "2"
services:
  test_server:
    build:
      dockerfile: ./dockerfiles/test.Dockerfile
      context: ../
    environment:
      - MONGO_URL=mongodb://db:27017/heroku
      - BRIDGE_ENDPOINT=http://api.staging.storj.io
    ports:
      - "8000:8000"
    links:
      - test_db:db
  test_db:
    build:
      dockerfile: ./db.Dockerfile
      context: ./
